<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8ebb9eeb-02e2-49c6-ada9-e14634e4aeb7</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.6" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.ReDoc" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="8.0.0" />
  </ItemGroup>

<ItemGroup>
	<None Update="appsettings.json">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="appsettings.Development.json">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IssueManager.Core\IssueManager.Core.csproj" />
  </ItemGroup>

</Project>
